POST http://localhost:8080/api/v1/user HTTP/1.1
content-type: application/json

{
    "username": "sample",
    "password": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET http://localhost:8080/api/v1/helloworld HTTP/1.1
